// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf C++ Version: 5.29.0

#include "auth.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace user {
namespace auth {

inline constexpr parseTokenResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : userid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        expiretimeseconds_{::int64_t{0}},
        platformid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR parseTokenResp::parseTokenResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct parseTokenRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR parseTokenRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~parseTokenRespDefaultTypeInternal() {}
  union {
    parseTokenResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 parseTokenRespDefaultTypeInternal _parseTokenResp_default_instance_;

inline constexpr parseTokenReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR parseTokenReq::parseTokenReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct parseTokenReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR parseTokenReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~parseTokenReqDefaultTypeInternal() {}
  union {
    parseTokenReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 parseTokenReqDefaultTypeInternal _parseTokenReq_default_instance_;

inline constexpr getAdminTokenResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        expiretimeseconds_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR getAdminTokenResp::getAdminTokenResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct getAdminTokenRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR getAdminTokenRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~getAdminTokenRespDefaultTypeInternal() {}
  union {
    getAdminTokenResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 getAdminTokenRespDefaultTypeInternal _getAdminTokenResp_default_instance_;

inline constexpr getAdminTokenReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : userid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        secret_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR getAdminTokenReq::getAdminTokenReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct getAdminTokenReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR getAdminTokenReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~getAdminTokenReqDefaultTypeInternal() {}
  union {
    getAdminTokenReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 getAdminTokenReqDefaultTypeInternal _getAdminTokenReq_default_instance_;
}  // namespace auth
}  // namespace user
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_auth_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_auth_2eproto = nullptr;
const ::uint32_t
    TableStruct_auth_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::auth::getAdminTokenReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::auth::getAdminTokenReq, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::user::auth::getAdminTokenReq, _impl_.secret_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::auth::getAdminTokenResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::auth::getAdminTokenResp, _impl_.token_),
        PROTOBUF_FIELD_OFFSET(::user::auth::getAdminTokenResp, _impl_.expiretimeseconds_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenReq, _impl_.token_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenResp, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenResp, _impl_.platformid_),
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenResp, _impl_.expiretimeseconds_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::user::auth::getAdminTokenReq)},
        {10, -1, -1, sizeof(::user::auth::getAdminTokenResp)},
        {20, -1, -1, sizeof(::user::auth::parseTokenReq)},
        {29, -1, -1, sizeof(::user::auth::parseTokenResp)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::user::auth::_getAdminTokenReq_default_instance_._instance,
    &::user::auth::_getAdminTokenResp_default_instance_._instance,
    &::user::auth::_parseTokenReq_default_instance_._instance,
    &::user::auth::_parseTokenResp_default_instance_._instance,
};
const char descriptor_table_protodef_auth_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nauth.proto\022\tuser.auth\"2\n\020getAdminToken"
    "Req\022\016\n\006userID\030\001 \001(\t\022\016\n\006secret\030\002 \001(\t\"=\n\021g"
    "etAdminTokenResp\022\r\n\005token\030\001 \001(\t\022\031\n\021expir"
    "eTimeSeconds\030\002 \001(\003\"\036\n\rparseTokenReq\022\r\n\005t"
    "oken\030\001 \001(\t\"O\n\016parseTokenResp\022\016\n\006userID\030\001"
    " \001(\t\022\022\n\nplatformID\030\002 \001(\005\022\031\n\021expireTimeSe"
    "conds\030\003 \001(\0032\225\001\n\004Auth\022J\n\rgetAdminToken\022\033."
    "user.auth.getAdminTokenReq\032\034.user.auth.g"
    "etAdminTokenResp\022A\n\nparseToken\022\030.user.au"
    "th.parseTokenReq\032\031.user.auth.parseTokenR"
    "espb\006proto3"
};
static ::absl::once_flag descriptor_table_auth_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_auth_2eproto = {
    false,
    false,
    411,
    descriptor_table_protodef_auth_2eproto,
    "auth.proto",
    &descriptor_table_auth_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_auth_2eproto::offsets,
    file_level_enum_descriptors_auth_2eproto,
    file_level_service_descriptors_auth_2eproto,
};
namespace user {
namespace auth {
// ===================================================================

class getAdminTokenReq::_Internal {
 public:
};

getAdminTokenReq::getAdminTokenReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.auth.getAdminTokenReq)
}
inline PROTOBUF_NDEBUG_INLINE getAdminTokenReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::auth::getAdminTokenReq& from_msg)
      : userid_(arena, from.userid_),
        secret_(arena, from.secret_),
        _cached_size_{0} {}

getAdminTokenReq::getAdminTokenReq(
    ::google::protobuf::Arena* arena,
    const getAdminTokenReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  getAdminTokenReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:user.auth.getAdminTokenReq)
}
inline PROTOBUF_NDEBUG_INLINE getAdminTokenReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : userid_(arena),
        secret_(arena),
        _cached_size_{0} {}

inline void getAdminTokenReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
getAdminTokenReq::~getAdminTokenReq() {
  // @@protoc_insertion_point(destructor:user.auth.getAdminTokenReq)
  SharedDtor(*this);
}
inline void getAdminTokenReq::SharedDtor(MessageLite& self) {
  getAdminTokenReq& this_ = static_cast<getAdminTokenReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.userid_.Destroy();
  this_._impl_.secret_.Destroy();
  this_._impl_.~Impl_();
}

inline void* getAdminTokenReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) getAdminTokenReq(arena);
}
constexpr auto getAdminTokenReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(getAdminTokenReq),
                                            alignof(getAdminTokenReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull getAdminTokenReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_getAdminTokenReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &getAdminTokenReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<getAdminTokenReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &getAdminTokenReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<getAdminTokenReq>(), &getAdminTokenReq::ByteSizeLong,
            &getAdminTokenReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(getAdminTokenReq, _impl_._cached_size_),
        false,
    },
    &getAdminTokenReq::kDescriptorMethods,
    &descriptor_table_auth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* getAdminTokenReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 47, 2> getAdminTokenReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::auth::getAdminTokenReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string secret = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(getAdminTokenReq, _impl_.secret_)}},
    // string userID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(getAdminTokenReq, _impl_.userid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string userID = 1;
    {PROTOBUF_FIELD_OFFSET(getAdminTokenReq, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string secret = 2;
    {PROTOBUF_FIELD_OFFSET(getAdminTokenReq, _impl_.secret_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\6\6\0\0\0\0\0"
    "user.auth.getAdminTokenReq"
    "userID"
    "secret"
  }},
};

PROTOBUF_NOINLINE void getAdminTokenReq::Clear() {
// @@protoc_insertion_point(message_clear_start:user.auth.getAdminTokenReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userid_.ClearToEmpty();
  _impl_.secret_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* getAdminTokenReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const getAdminTokenReq& this_ = static_cast<const getAdminTokenReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* getAdminTokenReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const getAdminTokenReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.auth.getAdminTokenReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string userID = 1;
          if (!this_._internal_userid().empty()) {
            const std::string& _s = this_._internal_userid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.auth.getAdminTokenReq.userID");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string secret = 2;
          if (!this_._internal_secret().empty()) {
            const std::string& _s = this_._internal_secret();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.auth.getAdminTokenReq.secret");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.auth.getAdminTokenReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t getAdminTokenReq::ByteSizeLong(const MessageLite& base) {
          const getAdminTokenReq& this_ = static_cast<const getAdminTokenReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t getAdminTokenReq::ByteSizeLong() const {
          const getAdminTokenReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.auth.getAdminTokenReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string userID = 1;
            if (!this_._internal_userid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_userid());
            }
            // string secret = 2;
            if (!this_._internal_secret().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_secret());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void getAdminTokenReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<getAdminTokenReq*>(&to_msg);
  auto& from = static_cast<const getAdminTokenReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.auth.getAdminTokenReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_userid().empty()) {
    _this->_internal_set_userid(from._internal_userid());
  }
  if (!from._internal_secret().empty()) {
    _this->_internal_set_secret(from._internal_secret());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void getAdminTokenReq::CopyFrom(const getAdminTokenReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.auth.getAdminTokenReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void getAdminTokenReq::InternalSwap(getAdminTokenReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userid_, &other->_impl_.userid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.secret_, &other->_impl_.secret_, arena);
}

::google::protobuf::Metadata getAdminTokenReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class getAdminTokenResp::_Internal {
 public:
};

getAdminTokenResp::getAdminTokenResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.auth.getAdminTokenResp)
}
inline PROTOBUF_NDEBUG_INLINE getAdminTokenResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::auth::getAdminTokenResp& from_msg)
      : token_(arena, from.token_),
        _cached_size_{0} {}

getAdminTokenResp::getAdminTokenResp(
    ::google::protobuf::Arena* arena,
    const getAdminTokenResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  getAdminTokenResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.expiretimeseconds_ = from._impl_.expiretimeseconds_;

  // @@protoc_insertion_point(copy_constructor:user.auth.getAdminTokenResp)
}
inline PROTOBUF_NDEBUG_INLINE getAdminTokenResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        _cached_size_{0} {}

inline void getAdminTokenResp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.expiretimeseconds_ = {};
}
getAdminTokenResp::~getAdminTokenResp() {
  // @@protoc_insertion_point(destructor:user.auth.getAdminTokenResp)
  SharedDtor(*this);
}
inline void getAdminTokenResp::SharedDtor(MessageLite& self) {
  getAdminTokenResp& this_ = static_cast<getAdminTokenResp&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* getAdminTokenResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) getAdminTokenResp(arena);
}
constexpr auto getAdminTokenResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(getAdminTokenResp),
                                            alignof(getAdminTokenResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull getAdminTokenResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_getAdminTokenResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &getAdminTokenResp::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<getAdminTokenResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &getAdminTokenResp::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<getAdminTokenResp>(), &getAdminTokenResp::ByteSizeLong,
            &getAdminTokenResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(getAdminTokenResp, _impl_._cached_size_),
        false,
    },
    &getAdminTokenResp::kDescriptorMethods,
    &descriptor_table_auth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* getAdminTokenResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 41, 2> getAdminTokenResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::auth::getAdminTokenResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 expireTimeSeconds = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(getAdminTokenResp, _impl_.expiretimeseconds_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(getAdminTokenResp, _impl_.expiretimeseconds_)}},
    // string token = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(getAdminTokenResp, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string token = 1;
    {PROTOBUF_FIELD_OFFSET(getAdminTokenResp, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 expireTimeSeconds = 2;
    {PROTOBUF_FIELD_OFFSET(getAdminTokenResp, _impl_.expiretimeseconds_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\33\5\0\0\0\0\0\0"
    "user.auth.getAdminTokenResp"
    "token"
  }},
};

PROTOBUF_NOINLINE void getAdminTokenResp::Clear() {
// @@protoc_insertion_point(message_clear_start:user.auth.getAdminTokenResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.expiretimeseconds_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* getAdminTokenResp::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const getAdminTokenResp& this_ = static_cast<const getAdminTokenResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* getAdminTokenResp::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const getAdminTokenResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.auth.getAdminTokenResp)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string token = 1;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.auth.getAdminTokenResp.token");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int64 expireTimeSeconds = 2;
          if (this_._internal_expiretimeseconds() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_expiretimeseconds(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.auth.getAdminTokenResp)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t getAdminTokenResp::ByteSizeLong(const MessageLite& base) {
          const getAdminTokenResp& this_ = static_cast<const getAdminTokenResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t getAdminTokenResp::ByteSizeLong() const {
          const getAdminTokenResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.auth.getAdminTokenResp)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string token = 1;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
            // int64 expireTimeSeconds = 2;
            if (this_._internal_expiretimeseconds() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_expiretimeseconds());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void getAdminTokenResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<getAdminTokenResp*>(&to_msg);
  auto& from = static_cast<const getAdminTokenResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.auth.getAdminTokenResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_expiretimeseconds() != 0) {
    _this->_impl_.expiretimeseconds_ = from._impl_.expiretimeseconds_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void getAdminTokenResp::CopyFrom(const getAdminTokenResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.auth.getAdminTokenResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void getAdminTokenResp::InternalSwap(getAdminTokenResp* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
        swap(_impl_.expiretimeseconds_, other->_impl_.expiretimeseconds_);
}

::google::protobuf::Metadata getAdminTokenResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class parseTokenReq::_Internal {
 public:
};

parseTokenReq::parseTokenReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.auth.parseTokenReq)
}
inline PROTOBUF_NDEBUG_INLINE parseTokenReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::auth::parseTokenReq& from_msg)
      : token_(arena, from.token_),
        _cached_size_{0} {}

parseTokenReq::parseTokenReq(
    ::google::protobuf::Arena* arena,
    const parseTokenReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  parseTokenReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:user.auth.parseTokenReq)
}
inline PROTOBUF_NDEBUG_INLINE parseTokenReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        _cached_size_{0} {}

inline void parseTokenReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
parseTokenReq::~parseTokenReq() {
  // @@protoc_insertion_point(destructor:user.auth.parseTokenReq)
  SharedDtor(*this);
}
inline void parseTokenReq::SharedDtor(MessageLite& self) {
  parseTokenReq& this_ = static_cast<parseTokenReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* parseTokenReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) parseTokenReq(arena);
}
constexpr auto parseTokenReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(parseTokenReq),
                                            alignof(parseTokenReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull parseTokenReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_parseTokenReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &parseTokenReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<parseTokenReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &parseTokenReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<parseTokenReq>(), &parseTokenReq::ByteSizeLong,
            &parseTokenReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(parseTokenReq, _impl_._cached_size_),
        false,
    },
    &parseTokenReq::kDescriptorMethods,
    &descriptor_table_auth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* parseTokenReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 37, 2> parseTokenReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::auth::parseTokenReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string token = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(parseTokenReq, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string token = 1;
    {PROTOBUF_FIELD_OFFSET(parseTokenReq, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\5\0\0\0\0\0\0"
    "user.auth.parseTokenReq"
    "token"
  }},
};

PROTOBUF_NOINLINE void parseTokenReq::Clear() {
// @@protoc_insertion_point(message_clear_start:user.auth.parseTokenReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* parseTokenReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const parseTokenReq& this_ = static_cast<const parseTokenReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* parseTokenReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const parseTokenReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.auth.parseTokenReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string token = 1;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.auth.parseTokenReq.token");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.auth.parseTokenReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t parseTokenReq::ByteSizeLong(const MessageLite& base) {
          const parseTokenReq& this_ = static_cast<const parseTokenReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t parseTokenReq::ByteSizeLong() const {
          const parseTokenReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.auth.parseTokenReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string token = 1;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void parseTokenReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<parseTokenReq*>(&to_msg);
  auto& from = static_cast<const parseTokenReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.auth.parseTokenReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void parseTokenReq::CopyFrom(const parseTokenReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.auth.parseTokenReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void parseTokenReq::InternalSwap(parseTokenReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
}

::google::protobuf::Metadata parseTokenReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class parseTokenResp::_Internal {
 public:
};

parseTokenResp::parseTokenResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.auth.parseTokenResp)
}
inline PROTOBUF_NDEBUG_INLINE parseTokenResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::auth::parseTokenResp& from_msg)
      : userid_(arena, from.userid_),
        _cached_size_{0} {}

parseTokenResp::parseTokenResp(
    ::google::protobuf::Arena* arena,
    const parseTokenResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  parseTokenResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, expiretimeseconds_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, expiretimeseconds_),
           offsetof(Impl_, platformid_) -
               offsetof(Impl_, expiretimeseconds_) +
               sizeof(Impl_::platformid_));

  // @@protoc_insertion_point(copy_constructor:user.auth.parseTokenResp)
}
inline PROTOBUF_NDEBUG_INLINE parseTokenResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : userid_(arena),
        _cached_size_{0} {}

inline void parseTokenResp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, expiretimeseconds_),
           0,
           offsetof(Impl_, platformid_) -
               offsetof(Impl_, expiretimeseconds_) +
               sizeof(Impl_::platformid_));
}
parseTokenResp::~parseTokenResp() {
  // @@protoc_insertion_point(destructor:user.auth.parseTokenResp)
  SharedDtor(*this);
}
inline void parseTokenResp::SharedDtor(MessageLite& self) {
  parseTokenResp& this_ = static_cast<parseTokenResp&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.userid_.Destroy();
  this_._impl_.~Impl_();
}

inline void* parseTokenResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) parseTokenResp(arena);
}
constexpr auto parseTokenResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(parseTokenResp),
                                            alignof(parseTokenResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull parseTokenResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_parseTokenResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &parseTokenResp::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<parseTokenResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &parseTokenResp::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<parseTokenResp>(), &parseTokenResp::ByteSizeLong,
            &parseTokenResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_._cached_size_),
        false,
    },
    &parseTokenResp::kDescriptorMethods,
    &descriptor_table_auth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* parseTokenResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 39, 2> parseTokenResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::auth::parseTokenResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string userID = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.userid_)}},
    // int32 platformID = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(parseTokenResp, _impl_.platformid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.platformid_)}},
    // int64 expireTimeSeconds = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(parseTokenResp, _impl_.expiretimeseconds_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.expiretimeseconds_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string userID = 1;
    {PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 platformID = 2;
    {PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.platformid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 expireTimeSeconds = 3;
    {PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.expiretimeseconds_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\30\6\0\0\0\0\0\0"
    "user.auth.parseTokenResp"
    "userID"
  }},
};

PROTOBUF_NOINLINE void parseTokenResp::Clear() {
// @@protoc_insertion_point(message_clear_start:user.auth.parseTokenResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userid_.ClearToEmpty();
  ::memset(&_impl_.expiretimeseconds_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.platformid_) -
      reinterpret_cast<char*>(&_impl_.expiretimeseconds_)) + sizeof(_impl_.platformid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* parseTokenResp::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const parseTokenResp& this_ = static_cast<const parseTokenResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* parseTokenResp::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const parseTokenResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.auth.parseTokenResp)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string userID = 1;
          if (!this_._internal_userid().empty()) {
            const std::string& _s = this_._internal_userid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.auth.parseTokenResp.userID");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int32 platformID = 2;
          if (this_._internal_platformid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_platformid(), target);
          }

          // int64 expireTimeSeconds = 3;
          if (this_._internal_expiretimeseconds() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<3>(
                    stream, this_._internal_expiretimeseconds(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.auth.parseTokenResp)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t parseTokenResp::ByteSizeLong(const MessageLite& base) {
          const parseTokenResp& this_ = static_cast<const parseTokenResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t parseTokenResp::ByteSizeLong() const {
          const parseTokenResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.auth.parseTokenResp)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string userID = 1;
            if (!this_._internal_userid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_userid());
            }
            // int64 expireTimeSeconds = 3;
            if (this_._internal_expiretimeseconds() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_expiretimeseconds());
            }
            // int32 platformID = 2;
            if (this_._internal_platformid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_platformid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void parseTokenResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<parseTokenResp*>(&to_msg);
  auto& from = static_cast<const parseTokenResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.auth.parseTokenResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_userid().empty()) {
    _this->_internal_set_userid(from._internal_userid());
  }
  if (from._internal_expiretimeseconds() != 0) {
    _this->_impl_.expiretimeseconds_ = from._impl_.expiretimeseconds_;
  }
  if (from._internal_platformid() != 0) {
    _this->_impl_.platformid_ = from._impl_.platformid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void parseTokenResp::CopyFrom(const parseTokenResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.auth.parseTokenResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void parseTokenResp::InternalSwap(parseTokenResp* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userid_, &other->_impl_.userid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.platformid_)
      + sizeof(parseTokenResp::_impl_.platformid_)
      - PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.expiretimeseconds_)>(
          reinterpret_cast<char*>(&_impl_.expiretimeseconds_),
          reinterpret_cast<char*>(&other->_impl_.expiretimeseconds_));
}

::google::protobuf::Metadata parseTokenResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace auth
}  // namespace user
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_auth_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
