// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: auth.proto
#ifndef GRPC_auth_2eproto__INCLUDED
#define GRPC_auth_2eproto__INCLUDED

#include "auth.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace user {
namespace auth {

class Auth final {
 public:
  static constexpr char const* service_full_name() {
    return "user.auth.Auth";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 获取管理员 token
    virtual ::grpc::Status getAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::user::auth::getAdminTokenResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getAdminTokenResp>> AsyncgetAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getAdminTokenResp>>(AsyncgetAdminTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getAdminTokenResp>> PrepareAsyncgetAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getAdminTokenResp>>(PrepareAsyncgetAdminTokenRaw(context, request, cq));
    }
    // 解析 token
    virtual ::grpc::Status parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::user::auth::parseTokenResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::parseTokenResp>> AsyncparseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::parseTokenResp>>(AsyncparseTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::parseTokenResp>> PrepareAsyncparseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::parseTokenResp>>(PrepareAsyncparseTokenRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 获取管理员 token
      virtual void getAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq* request, ::user::auth::getAdminTokenResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq* request, ::user::auth::getAdminTokenResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 解析 token
      virtual void parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::parseTokenResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::parseTokenResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getAdminTokenResp>* AsyncgetAdminTokenRaw(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getAdminTokenResp>* PrepareAsyncgetAdminTokenRaw(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::parseTokenResp>* AsyncparseTokenRaw(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::parseTokenResp>* PrepareAsyncparseTokenRaw(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status getAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::user::auth::getAdminTokenResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::getAdminTokenResp>> AsyncgetAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::getAdminTokenResp>>(AsyncgetAdminTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::getAdminTokenResp>> PrepareAsyncgetAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::getAdminTokenResp>>(PrepareAsyncgetAdminTokenRaw(context, request, cq));
    }
    ::grpc::Status parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::user::auth::parseTokenResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::parseTokenResp>> AsyncparseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::parseTokenResp>>(AsyncparseTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::parseTokenResp>> PrepareAsyncparseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::parseTokenResp>>(PrepareAsyncparseTokenRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void getAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq* request, ::user::auth::getAdminTokenResp* response, std::function<void(::grpc::Status)>) override;
      void getAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq* request, ::user::auth::getAdminTokenResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::parseTokenResp* response, std::function<void(::grpc::Status)>) override;
      void parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::parseTokenResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::user::auth::getAdminTokenResp>* AsyncgetAdminTokenRaw(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::auth::getAdminTokenResp>* PrepareAsyncgetAdminTokenRaw(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::auth::parseTokenResp>* AsyncparseTokenRaw(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::auth::parseTokenResp>* PrepareAsyncparseTokenRaw(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getAdminToken_;
    const ::grpc::internal::RpcMethod rpcmethod_parseToken_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 获取管理员 token
    virtual ::grpc::Status getAdminToken(::grpc::ServerContext* context, const ::user::auth::getAdminTokenReq* request, ::user::auth::getAdminTokenResp* response);
    // 解析 token
    virtual ::grpc::Status parseToken(::grpc::ServerContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::parseTokenResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getAdminToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getAdminToken() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getAdminToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getAdminToken(::grpc::ServerContext* /*context*/, const ::user::auth::getAdminTokenReq* /*request*/, ::user::auth::getAdminTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetAdminToken(::grpc::ServerContext* context, ::user::auth::getAdminTokenReq* request, ::grpc::ServerAsyncResponseWriter< ::user::auth::getAdminTokenResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_parseToken() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::parseTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestparseToken(::grpc::ServerContext* context, ::user::auth::parseTokenReq* request, ::grpc::ServerAsyncResponseWriter< ::user::auth::parseTokenResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getAdminToken<WithAsyncMethod_parseToken<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_getAdminToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_getAdminToken() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::user::auth::getAdminTokenReq, ::user::auth::getAdminTokenResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::auth::getAdminTokenReq* request, ::user::auth::getAdminTokenResp* response) { return this->getAdminToken(context, request, response); }));}
    void SetMessageAllocatorFor_getAdminToken(
        ::grpc::MessageAllocator< ::user::auth::getAdminTokenReq, ::user::auth::getAdminTokenResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::auth::getAdminTokenReq, ::user::auth::getAdminTokenResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_getAdminToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getAdminToken(::grpc::ServerContext* /*context*/, const ::user::auth::getAdminTokenReq* /*request*/, ::user::auth::getAdminTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getAdminToken(
      ::grpc::CallbackServerContext* /*context*/, const ::user::auth::getAdminTokenReq* /*request*/, ::user::auth::getAdminTokenResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_parseToken() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::user::auth::parseTokenReq, ::user::auth::parseTokenResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::parseTokenResp* response) { return this->parseToken(context, request, response); }));}
    void SetMessageAllocatorFor_parseToken(
        ::grpc::MessageAllocator< ::user::auth::parseTokenReq, ::user::auth::parseTokenResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::auth::parseTokenReq, ::user::auth::parseTokenResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::parseTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* parseToken(
      ::grpc::CallbackServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::parseTokenResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_getAdminToken<WithCallbackMethod_parseToken<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getAdminToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getAdminToken() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getAdminToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getAdminToken(::grpc::ServerContext* /*context*/, const ::user::auth::getAdminTokenReq* /*request*/, ::user::auth::getAdminTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_parseToken() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::parseTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getAdminToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getAdminToken() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getAdminToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getAdminToken(::grpc::ServerContext* /*context*/, const ::user::auth::getAdminTokenReq* /*request*/, ::user::auth::getAdminTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetAdminToken(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_parseToken() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::parseTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestparseToken(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_getAdminToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_getAdminToken() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getAdminToken(context, request, response); }));
    }
    ~WithRawCallbackMethod_getAdminToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getAdminToken(::grpc::ServerContext* /*context*/, const ::user::auth::getAdminTokenReq* /*request*/, ::user::auth::getAdminTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getAdminToken(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_parseToken() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->parseToken(context, request, response); }));
    }
    ~WithRawCallbackMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::parseTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* parseToken(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getAdminToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getAdminToken() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::auth::getAdminTokenReq, ::user::auth::getAdminTokenResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::auth::getAdminTokenReq, ::user::auth::getAdminTokenResp>* streamer) {
                       return this->StreamedgetAdminToken(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getAdminToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getAdminToken(::grpc::ServerContext* /*context*/, const ::user::auth::getAdminTokenReq* /*request*/, ::user::auth::getAdminTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetAdminToken(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::auth::getAdminTokenReq,::user::auth::getAdminTokenResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_parseToken() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::auth::parseTokenReq, ::user::auth::parseTokenResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::auth::parseTokenReq, ::user::auth::parseTokenResp>* streamer) {
                       return this->StreamedparseToken(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::parseTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedparseToken(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::auth::parseTokenReq,::user::auth::parseTokenResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getAdminToken<WithStreamedUnaryMethod_parseToken<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getAdminToken<WithStreamedUnaryMethod_parseToken<Service > > StreamedService;
};

}  // namespace auth
}  // namespace user


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_auth_2eproto__INCLUDED
