// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user/auth.proto
// Protobuf C++ Version: 5.29.0

#include "auth.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace user {
namespace auth {

inline constexpr registerUserResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR registerUserResp::registerUserResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct registerUserRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR registerUserRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~registerUserRespDefaultTypeInternal() {}
  union {
    registerUserResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 registerUserRespDefaultTypeInternal _registerUserResp_default_instance_;

inline constexpr registerUserReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        faceurl_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        userid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR registerUserReq::registerUserReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct registerUserReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR registerUserReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~registerUserReqDefaultTypeInternal() {}
  union {
    registerUserReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 registerUserReqDefaultTypeInternal _registerUserReq_default_instance_;

inline constexpr parseTokenResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : userid_{0},
        platformid_{0},
        expiretimeseconds_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR parseTokenResp::parseTokenResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct parseTokenRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR parseTokenRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~parseTokenRespDefaultTypeInternal() {}
  union {
    parseTokenResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 parseTokenRespDefaultTypeInternal _parseTokenResp_default_instance_;

inline constexpr parseTokenReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR parseTokenReq::parseTokenReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct parseTokenReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR parseTokenReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~parseTokenReqDefaultTypeInternal() {}
  union {
    parseTokenReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 parseTokenReqDefaultTypeInternal _parseTokenReq_default_instance_;

inline constexpr getUserTokenResp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        expiretimeseconds_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR getUserTokenResp::getUserTokenResp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct getUserTokenRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR getUserTokenRespDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~getUserTokenRespDefaultTypeInternal() {}
  union {
    getUserTokenResp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 getUserTokenRespDefaultTypeInternal _getUserTokenResp_default_instance_;

inline constexpr getUserTokenReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : secret_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        userid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR getUserTokenReq::getUserTokenReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct getUserTokenReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR getUserTokenReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~getUserTokenReqDefaultTypeInternal() {}
  union {
    getUserTokenReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 getUserTokenReqDefaultTypeInternal _getUserTokenReq_default_instance_;
}  // namespace auth
}  // namespace user
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_user_2fauth_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_user_2fauth_2eproto = nullptr;
const ::uint32_t
    TableStruct_user_2fauth_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::auth::getUserTokenReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::auth::getUserTokenReq, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::user::auth::getUserTokenReq, _impl_.secret_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::auth::getUserTokenResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::auth::getUserTokenResp, _impl_.token_),
        PROTOBUF_FIELD_OFFSET(::user::auth::getUserTokenResp, _impl_.expiretimeseconds_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenReq, _impl_.token_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenResp, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenResp, _impl_.platformid_),
        PROTOBUF_FIELD_OFFSET(::user::auth::parseTokenResp, _impl_.expiretimeseconds_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::auth::registerUserReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::auth::registerUserReq, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::user::auth::registerUserReq, _impl_.nickname_),
        PROTOBUF_FIELD_OFFSET(::user::auth::registerUserReq, _impl_.faceurl_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::user::auth::registerUserResp, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::user::auth::registerUserResp, _impl_.result_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::user::auth::getUserTokenReq)},
        {10, -1, -1, sizeof(::user::auth::getUserTokenResp)},
        {20, -1, -1, sizeof(::user::auth::parseTokenReq)},
        {29, -1, -1, sizeof(::user::auth::parseTokenResp)},
        {40, -1, -1, sizeof(::user::auth::registerUserReq)},
        {51, -1, -1, sizeof(::user::auth::registerUserResp)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::user::auth::_getUserTokenReq_default_instance_._instance,
    &::user::auth::_getUserTokenResp_default_instance_._instance,
    &::user::auth::_parseTokenReq_default_instance_._instance,
    &::user::auth::_parseTokenResp_default_instance_._instance,
    &::user::auth::_registerUserReq_default_instance_._instance,
    &::user::auth::_registerUserResp_default_instance_._instance,
};
const char descriptor_table_protodef_user_2fauth_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017user/auth.proto\022\tuser.auth\"1\n\017getUserT"
    "okenReq\022\016\n\006userID\030\001 \001(\005\022\016\n\006secret\030\002 \001(\t\""
    "<\n\020getUserTokenResp\022\r\n\005token\030\001 \001(\t\022\031\n\021ex"
    "pireTimeSeconds\030\002 \001(\003\"\036\n\rparseTokenReq\022\r"
    "\n\005token\030\001 \001(\t\"O\n\016parseTokenResp\022\016\n\006userI"
    "D\030\001 \001(\005\022\022\n\nplatformID\030\002 \001(\005\022\031\n\021expireTim"
    "eSeconds\030\003 \001(\003\"D\n\017registerUserReq\022\016\n\006use"
    "rID\030\001 \001(\005\022\020\n\010nickName\030\002 \001(\t\022\017\n\007faceURL\030\003"
    " \001(\t\"\"\n\020registerUserResp\022\016\n\006result\030\001 \001(\010"
    "2\332\001\n\004Auth\022G\n\014getUserToken\022\032.user.auth.ge"
    "tUserTokenReq\032\033.user.auth.getUserTokenRe"
    "sp\022A\n\nparseToken\022\030.user.auth.parseTokenR"
    "eq\032\031.user.auth.parseTokenResp\022F\n\013registe"
    "rUer\022\032.user.auth.registerUserReq\032\033.user."
    "auth.registerUserRespb\006proto3"
};
static ::absl::once_flag descriptor_table_user_2fauth_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_user_2fauth_2eproto = {
    false,
    false,
    589,
    descriptor_table_protodef_user_2fauth_2eproto,
    "user/auth.proto",
    &descriptor_table_user_2fauth_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_user_2fauth_2eproto::offsets,
    file_level_enum_descriptors_user_2fauth_2eproto,
    file_level_service_descriptors_user_2fauth_2eproto,
};
namespace user {
namespace auth {
// ===================================================================

class getUserTokenReq::_Internal {
 public:
};

getUserTokenReq::getUserTokenReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.auth.getUserTokenReq)
}
inline PROTOBUF_NDEBUG_INLINE getUserTokenReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::auth::getUserTokenReq& from_msg)
      : secret_(arena, from.secret_),
        _cached_size_{0} {}

getUserTokenReq::getUserTokenReq(
    ::google::protobuf::Arena* arena,
    const getUserTokenReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  getUserTokenReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.userid_ = from._impl_.userid_;

  // @@protoc_insertion_point(copy_constructor:user.auth.getUserTokenReq)
}
inline PROTOBUF_NDEBUG_INLINE getUserTokenReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : secret_(arena),
        _cached_size_{0} {}

inline void getUserTokenReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.userid_ = {};
}
getUserTokenReq::~getUserTokenReq() {
  // @@protoc_insertion_point(destructor:user.auth.getUserTokenReq)
  SharedDtor(*this);
}
inline void getUserTokenReq::SharedDtor(MessageLite& self) {
  getUserTokenReq& this_ = static_cast<getUserTokenReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.secret_.Destroy();
  this_._impl_.~Impl_();
}

inline void* getUserTokenReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) getUserTokenReq(arena);
}
constexpr auto getUserTokenReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(getUserTokenReq),
                                            alignof(getUserTokenReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull getUserTokenReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_getUserTokenReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &getUserTokenReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<getUserTokenReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &getUserTokenReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<getUserTokenReq>(), &getUserTokenReq::ByteSizeLong,
            &getUserTokenReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(getUserTokenReq, _impl_._cached_size_),
        false,
    },
    &getUserTokenReq::kDescriptorMethods,
    &descriptor_table_user_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* getUserTokenReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2> getUserTokenReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::auth::getUserTokenReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string secret = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(getUserTokenReq, _impl_.secret_)}},
    // int32 userID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(getUserTokenReq, _impl_.userid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(getUserTokenReq, _impl_.userid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 userID = 1;
    {PROTOBUF_FIELD_OFFSET(getUserTokenReq, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string secret = 2;
    {PROTOBUF_FIELD_OFFSET(getUserTokenReq, _impl_.secret_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\6\0\0\0\0\0"
    "user.auth.getUserTokenReq"
    "secret"
  }},
};

PROTOBUF_NOINLINE void getUserTokenReq::Clear() {
// @@protoc_insertion_point(message_clear_start:user.auth.getUserTokenReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.secret_.ClearToEmpty();
  _impl_.userid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* getUserTokenReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const getUserTokenReq& this_ = static_cast<const getUserTokenReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* getUserTokenReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const getUserTokenReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.auth.getUserTokenReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 userID = 1;
          if (this_._internal_userid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_userid(), target);
          }

          // string secret = 2;
          if (!this_._internal_secret().empty()) {
            const std::string& _s = this_._internal_secret();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.auth.getUserTokenReq.secret");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.auth.getUserTokenReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t getUserTokenReq::ByteSizeLong(const MessageLite& base) {
          const getUserTokenReq& this_ = static_cast<const getUserTokenReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t getUserTokenReq::ByteSizeLong() const {
          const getUserTokenReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.auth.getUserTokenReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string secret = 2;
            if (!this_._internal_secret().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_secret());
            }
            // int32 userID = 1;
            if (this_._internal_userid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_userid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void getUserTokenReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<getUserTokenReq*>(&to_msg);
  auto& from = static_cast<const getUserTokenReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.auth.getUserTokenReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_secret().empty()) {
    _this->_internal_set_secret(from._internal_secret());
  }
  if (from._internal_userid() != 0) {
    _this->_impl_.userid_ = from._impl_.userid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void getUserTokenReq::CopyFrom(const getUserTokenReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.auth.getUserTokenReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void getUserTokenReq::InternalSwap(getUserTokenReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.secret_, &other->_impl_.secret_, arena);
        swap(_impl_.userid_, other->_impl_.userid_);
}

::google::protobuf::Metadata getUserTokenReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class getUserTokenResp::_Internal {
 public:
};

getUserTokenResp::getUserTokenResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.auth.getUserTokenResp)
}
inline PROTOBUF_NDEBUG_INLINE getUserTokenResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::auth::getUserTokenResp& from_msg)
      : token_(arena, from.token_),
        _cached_size_{0} {}

getUserTokenResp::getUserTokenResp(
    ::google::protobuf::Arena* arena,
    const getUserTokenResp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  getUserTokenResp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.expiretimeseconds_ = from._impl_.expiretimeseconds_;

  // @@protoc_insertion_point(copy_constructor:user.auth.getUserTokenResp)
}
inline PROTOBUF_NDEBUG_INLINE getUserTokenResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        _cached_size_{0} {}

inline void getUserTokenResp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.expiretimeseconds_ = {};
}
getUserTokenResp::~getUserTokenResp() {
  // @@protoc_insertion_point(destructor:user.auth.getUserTokenResp)
  SharedDtor(*this);
}
inline void getUserTokenResp::SharedDtor(MessageLite& self) {
  getUserTokenResp& this_ = static_cast<getUserTokenResp&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* getUserTokenResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) getUserTokenResp(arena);
}
constexpr auto getUserTokenResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(getUserTokenResp),
                                            alignof(getUserTokenResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull getUserTokenResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_getUserTokenResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &getUserTokenResp::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<getUserTokenResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &getUserTokenResp::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<getUserTokenResp>(), &getUserTokenResp::ByteSizeLong,
            &getUserTokenResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(getUserTokenResp, _impl_._cached_size_),
        false,
    },
    &getUserTokenResp::kDescriptorMethods,
    &descriptor_table_user_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* getUserTokenResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2> getUserTokenResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::auth::getUserTokenResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 expireTimeSeconds = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(getUserTokenResp, _impl_.expiretimeseconds_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(getUserTokenResp, _impl_.expiretimeseconds_)}},
    // string token = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(getUserTokenResp, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string token = 1;
    {PROTOBUF_FIELD_OFFSET(getUserTokenResp, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 expireTimeSeconds = 2;
    {PROTOBUF_FIELD_OFFSET(getUserTokenResp, _impl_.expiretimeseconds_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\32\5\0\0\0\0\0\0"
    "user.auth.getUserTokenResp"
    "token"
  }},
};

PROTOBUF_NOINLINE void getUserTokenResp::Clear() {
// @@protoc_insertion_point(message_clear_start:user.auth.getUserTokenResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.expiretimeseconds_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* getUserTokenResp::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const getUserTokenResp& this_ = static_cast<const getUserTokenResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* getUserTokenResp::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const getUserTokenResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.auth.getUserTokenResp)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string token = 1;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.auth.getUserTokenResp.token");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // int64 expireTimeSeconds = 2;
          if (this_._internal_expiretimeseconds() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<2>(
                    stream, this_._internal_expiretimeseconds(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.auth.getUserTokenResp)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t getUserTokenResp::ByteSizeLong(const MessageLite& base) {
          const getUserTokenResp& this_ = static_cast<const getUserTokenResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t getUserTokenResp::ByteSizeLong() const {
          const getUserTokenResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.auth.getUserTokenResp)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string token = 1;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
            // int64 expireTimeSeconds = 2;
            if (this_._internal_expiretimeseconds() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_expiretimeseconds());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void getUserTokenResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<getUserTokenResp*>(&to_msg);
  auto& from = static_cast<const getUserTokenResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.auth.getUserTokenResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_expiretimeseconds() != 0) {
    _this->_impl_.expiretimeseconds_ = from._impl_.expiretimeseconds_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void getUserTokenResp::CopyFrom(const getUserTokenResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.auth.getUserTokenResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void getUserTokenResp::InternalSwap(getUserTokenResp* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
        swap(_impl_.expiretimeseconds_, other->_impl_.expiretimeseconds_);
}

::google::protobuf::Metadata getUserTokenResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class parseTokenReq::_Internal {
 public:
};

parseTokenReq::parseTokenReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.auth.parseTokenReq)
}
inline PROTOBUF_NDEBUG_INLINE parseTokenReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::auth::parseTokenReq& from_msg)
      : token_(arena, from.token_),
        _cached_size_{0} {}

parseTokenReq::parseTokenReq(
    ::google::protobuf::Arena* arena,
    const parseTokenReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  parseTokenReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:user.auth.parseTokenReq)
}
inline PROTOBUF_NDEBUG_INLINE parseTokenReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        _cached_size_{0} {}

inline void parseTokenReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
parseTokenReq::~parseTokenReq() {
  // @@protoc_insertion_point(destructor:user.auth.parseTokenReq)
  SharedDtor(*this);
}
inline void parseTokenReq::SharedDtor(MessageLite& self) {
  parseTokenReq& this_ = static_cast<parseTokenReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* parseTokenReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) parseTokenReq(arena);
}
constexpr auto parseTokenReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(parseTokenReq),
                                            alignof(parseTokenReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull parseTokenReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_parseTokenReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &parseTokenReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<parseTokenReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &parseTokenReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<parseTokenReq>(), &parseTokenReq::ByteSizeLong,
            &parseTokenReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(parseTokenReq, _impl_._cached_size_),
        false,
    },
    &parseTokenReq::kDescriptorMethods,
    &descriptor_table_user_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* parseTokenReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 37, 2> parseTokenReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::auth::parseTokenReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string token = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(parseTokenReq, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string token = 1;
    {PROTOBUF_FIELD_OFFSET(parseTokenReq, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\5\0\0\0\0\0\0"
    "user.auth.parseTokenReq"
    "token"
  }},
};

PROTOBUF_NOINLINE void parseTokenReq::Clear() {
// @@protoc_insertion_point(message_clear_start:user.auth.parseTokenReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* parseTokenReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const parseTokenReq& this_ = static_cast<const parseTokenReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* parseTokenReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const parseTokenReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.auth.parseTokenReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string token = 1;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.auth.parseTokenReq.token");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.auth.parseTokenReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t parseTokenReq::ByteSizeLong(const MessageLite& base) {
          const parseTokenReq& this_ = static_cast<const parseTokenReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t parseTokenReq::ByteSizeLong() const {
          const parseTokenReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.auth.parseTokenReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string token = 1;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void parseTokenReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<parseTokenReq*>(&to_msg);
  auto& from = static_cast<const parseTokenReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.auth.parseTokenReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void parseTokenReq::CopyFrom(const parseTokenReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.auth.parseTokenReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void parseTokenReq::InternalSwap(parseTokenReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
}

::google::protobuf::Metadata parseTokenReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class parseTokenResp::_Internal {
 public:
};

parseTokenResp::parseTokenResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.auth.parseTokenResp)
}
parseTokenResp::parseTokenResp(
    ::google::protobuf::Arena* arena, const parseTokenResp& from)
    : parseTokenResp(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE parseTokenResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void parseTokenResp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, userid_),
           0,
           offsetof(Impl_, expiretimeseconds_) -
               offsetof(Impl_, userid_) +
               sizeof(Impl_::expiretimeseconds_));
}
parseTokenResp::~parseTokenResp() {
  // @@protoc_insertion_point(destructor:user.auth.parseTokenResp)
  SharedDtor(*this);
}
inline void parseTokenResp::SharedDtor(MessageLite& self) {
  parseTokenResp& this_ = static_cast<parseTokenResp&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* parseTokenResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) parseTokenResp(arena);
}
constexpr auto parseTokenResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(parseTokenResp),
                                            alignof(parseTokenResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull parseTokenResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_parseTokenResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &parseTokenResp::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<parseTokenResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &parseTokenResp::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<parseTokenResp>(), &parseTokenResp::ByteSizeLong,
            &parseTokenResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_._cached_size_),
        false,
    },
    &parseTokenResp::kDescriptorMethods,
    &descriptor_table_user_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* parseTokenResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> parseTokenResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::auth::parseTokenResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 userID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(parseTokenResp, _impl_.userid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.userid_)}},
    // int32 platformID = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(parseTokenResp, _impl_.platformid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.platformid_)}},
    // int64 expireTimeSeconds = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(parseTokenResp, _impl_.expiretimeseconds_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.expiretimeseconds_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 userID = 1;
    {PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 platformID = 2;
    {PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.platformid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 expireTimeSeconds = 3;
    {PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.expiretimeseconds_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void parseTokenResp::Clear() {
// @@protoc_insertion_point(message_clear_start:user.auth.parseTokenResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.userid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.expiretimeseconds_) -
      reinterpret_cast<char*>(&_impl_.userid_)) + sizeof(_impl_.expiretimeseconds_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* parseTokenResp::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const parseTokenResp& this_ = static_cast<const parseTokenResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* parseTokenResp::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const parseTokenResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.auth.parseTokenResp)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 userID = 1;
          if (this_._internal_userid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_userid(), target);
          }

          // int32 platformID = 2;
          if (this_._internal_platformid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_platformid(), target);
          }

          // int64 expireTimeSeconds = 3;
          if (this_._internal_expiretimeseconds() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<3>(
                    stream, this_._internal_expiretimeseconds(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.auth.parseTokenResp)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t parseTokenResp::ByteSizeLong(const MessageLite& base) {
          const parseTokenResp& this_ = static_cast<const parseTokenResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t parseTokenResp::ByteSizeLong() const {
          const parseTokenResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.auth.parseTokenResp)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 userID = 1;
            if (this_._internal_userid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_userid());
            }
            // int32 platformID = 2;
            if (this_._internal_platformid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_platformid());
            }
            // int64 expireTimeSeconds = 3;
            if (this_._internal_expiretimeseconds() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_expiretimeseconds());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void parseTokenResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<parseTokenResp*>(&to_msg);
  auto& from = static_cast<const parseTokenResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.auth.parseTokenResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_userid() != 0) {
    _this->_impl_.userid_ = from._impl_.userid_;
  }
  if (from._internal_platformid() != 0) {
    _this->_impl_.platformid_ = from._impl_.platformid_;
  }
  if (from._internal_expiretimeseconds() != 0) {
    _this->_impl_.expiretimeseconds_ = from._impl_.expiretimeseconds_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void parseTokenResp::CopyFrom(const parseTokenResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.auth.parseTokenResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void parseTokenResp::InternalSwap(parseTokenResp* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.expiretimeseconds_)
      + sizeof(parseTokenResp::_impl_.expiretimeseconds_)
      - PROTOBUF_FIELD_OFFSET(parseTokenResp, _impl_.userid_)>(
          reinterpret_cast<char*>(&_impl_.userid_),
          reinterpret_cast<char*>(&other->_impl_.userid_));
}

::google::protobuf::Metadata parseTokenResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class registerUserReq::_Internal {
 public:
};

registerUserReq::registerUserReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.auth.registerUserReq)
}
inline PROTOBUF_NDEBUG_INLINE registerUserReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::user::auth::registerUserReq& from_msg)
      : nickname_(arena, from.nickname_),
        faceurl_(arena, from.faceurl_),
        _cached_size_{0} {}

registerUserReq::registerUserReq(
    ::google::protobuf::Arena* arena,
    const registerUserReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  registerUserReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.userid_ = from._impl_.userid_;

  // @@protoc_insertion_point(copy_constructor:user.auth.registerUserReq)
}
inline PROTOBUF_NDEBUG_INLINE registerUserReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : nickname_(arena),
        faceurl_(arena),
        _cached_size_{0} {}

inline void registerUserReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.userid_ = {};
}
registerUserReq::~registerUserReq() {
  // @@protoc_insertion_point(destructor:user.auth.registerUserReq)
  SharedDtor(*this);
}
inline void registerUserReq::SharedDtor(MessageLite& self) {
  registerUserReq& this_ = static_cast<registerUserReq&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nickname_.Destroy();
  this_._impl_.faceurl_.Destroy();
  this_._impl_.~Impl_();
}

inline void* registerUserReq::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) registerUserReq(arena);
}
constexpr auto registerUserReq::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(registerUserReq),
                                            alignof(registerUserReq));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull registerUserReq::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_registerUserReq_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &registerUserReq::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<registerUserReq>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &registerUserReq::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<registerUserReq>(), &registerUserReq::ByteSizeLong,
            &registerUserReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(registerUserReq, _impl_._cached_size_),
        false,
    },
    &registerUserReq::kDescriptorMethods,
    &descriptor_table_user_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* registerUserReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 49, 2> registerUserReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::auth::registerUserReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 userID = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(registerUserReq, _impl_.userid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(registerUserReq, _impl_.userid_)}},
    // string nickName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(registerUserReq, _impl_.nickname_)}},
    // string faceURL = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(registerUserReq, _impl_.faceurl_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 userID = 1;
    {PROTOBUF_FIELD_OFFSET(registerUserReq, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string nickName = 2;
    {PROTOBUF_FIELD_OFFSET(registerUserReq, _impl_.nickname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string faceURL = 3;
    {PROTOBUF_FIELD_OFFSET(registerUserReq, _impl_.faceurl_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\0\10\7\0\0\0\0"
    "user.auth.registerUserReq"
    "nickName"
    "faceURL"
  }},
};

PROTOBUF_NOINLINE void registerUserReq::Clear() {
// @@protoc_insertion_point(message_clear_start:user.auth.registerUserReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.nickname_.ClearToEmpty();
  _impl_.faceurl_.ClearToEmpty();
  _impl_.userid_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* registerUserReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const registerUserReq& this_ = static_cast<const registerUserReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* registerUserReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const registerUserReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.auth.registerUserReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 userID = 1;
          if (this_._internal_userid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_userid(), target);
          }

          // string nickName = 2;
          if (!this_._internal_nickname().empty()) {
            const std::string& _s = this_._internal_nickname();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.auth.registerUserReq.nickName");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string faceURL = 3;
          if (!this_._internal_faceurl().empty()) {
            const std::string& _s = this_._internal_faceurl();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "user.auth.registerUserReq.faceURL");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.auth.registerUserReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t registerUserReq::ByteSizeLong(const MessageLite& base) {
          const registerUserReq& this_ = static_cast<const registerUserReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t registerUserReq::ByteSizeLong() const {
          const registerUserReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.auth.registerUserReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string nickName = 2;
            if (!this_._internal_nickname().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_nickname());
            }
            // string faceURL = 3;
            if (!this_._internal_faceurl().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_faceurl());
            }
            // int32 userID = 1;
            if (this_._internal_userid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_userid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void registerUserReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<registerUserReq*>(&to_msg);
  auto& from = static_cast<const registerUserReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.auth.registerUserReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_nickname().empty()) {
    _this->_internal_set_nickname(from._internal_nickname());
  }
  if (!from._internal_faceurl().empty()) {
    _this->_internal_set_faceurl(from._internal_faceurl());
  }
  if (from._internal_userid() != 0) {
    _this->_impl_.userid_ = from._impl_.userid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void registerUserReq::CopyFrom(const registerUserReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.auth.registerUserReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void registerUserReq::InternalSwap(registerUserReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nickname_, &other->_impl_.nickname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.faceurl_, &other->_impl_.faceurl_, arena);
        swap(_impl_.userid_, other->_impl_.userid_);
}

::google::protobuf::Metadata registerUserReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class registerUserResp::_Internal {
 public:
};

registerUserResp::registerUserResp(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:user.auth.registerUserResp)
}
registerUserResp::registerUserResp(
    ::google::protobuf::Arena* arena, const registerUserResp& from)
    : registerUserResp(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE registerUserResp::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void registerUserResp::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
registerUserResp::~registerUserResp() {
  // @@protoc_insertion_point(destructor:user.auth.registerUserResp)
  SharedDtor(*this);
}
inline void registerUserResp::SharedDtor(MessageLite& self) {
  registerUserResp& this_ = static_cast<registerUserResp&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* registerUserResp::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) registerUserResp(arena);
}
constexpr auto registerUserResp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(registerUserResp),
                                            alignof(registerUserResp));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull registerUserResp::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_registerUserResp_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &registerUserResp::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<registerUserResp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &registerUserResp::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<registerUserResp>(), &registerUserResp::ByteSizeLong,
            &registerUserResp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(registerUserResp, _impl_._cached_size_),
        false,
    },
    &registerUserResp::kDescriptorMethods,
    &descriptor_table_user_2fauth_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* registerUserResp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> registerUserResp::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::user::auth::registerUserResp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(registerUserResp, _impl_.result_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(registerUserResp, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool result = 1;
    {PROTOBUF_FIELD_OFFSET(registerUserResp, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void registerUserResp::Clear() {
// @@protoc_insertion_point(message_clear_start:user.auth.registerUserResp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* registerUserResp::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const registerUserResp& this_ = static_cast<const registerUserResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* registerUserResp::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const registerUserResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:user.auth.registerUserResp)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool result = 1;
          if (this_._internal_result() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_result(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:user.auth.registerUserResp)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t registerUserResp::ByteSizeLong(const MessageLite& base) {
          const registerUserResp& this_ = static_cast<const registerUserResp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t registerUserResp::ByteSizeLong() const {
          const registerUserResp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:user.auth.registerUserResp)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool result = 1;
            if (this_._internal_result() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void registerUserResp::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<registerUserResp*>(&to_msg);
  auto& from = static_cast<const registerUserResp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:user.auth.registerUserResp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void registerUserResp::CopyFrom(const registerUserResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:user.auth.registerUserResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void registerUserResp::InternalSwap(registerUserResp* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata registerUserResp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace auth
}  // namespace user
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_user_2fauth_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
