// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: auth.proto

#include "auth.pb.h"
#include "auth.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace user {
namespace auth {

static const char* Auth_method_names[] = {
  "/user.auth.Auth/getAdminToken",
  "/user.auth.Auth/parseToken",
};

std::unique_ptr< Auth::Stub> Auth::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Auth::Stub> stub(new Auth::Stub(channel, options));
  return stub;
}

Auth::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_getAdminToken_(Auth_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_parseToken_(Auth_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Auth::Stub::getAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::user::auth::getAdminTokenResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::auth::getAdminTokenReq, ::user::auth::getAdminTokenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_getAdminToken_, context, request, response);
}

void Auth::Stub::async::getAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq* request, ::user::auth::getAdminTokenResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::auth::getAdminTokenReq, ::user::auth::getAdminTokenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getAdminToken_, context, request, response, std::move(f));
}

void Auth::Stub::async::getAdminToken(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq* request, ::user::auth::getAdminTokenResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_getAdminToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::auth::getAdminTokenResp>* Auth::Stub::PrepareAsyncgetAdminTokenRaw(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::auth::getAdminTokenResp, ::user::auth::getAdminTokenReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_getAdminToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::auth::getAdminTokenResp>* Auth::Stub::AsyncgetAdminTokenRaw(::grpc::ClientContext* context, const ::user::auth::getAdminTokenReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgetAdminTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Auth::Stub::parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::user::auth::parseTokenResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::user::auth::parseTokenReq, ::user::auth::parseTokenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_parseToken_, context, request, response);
}

void Auth::Stub::async::parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::parseTokenResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::user::auth::parseTokenReq, ::user::auth::parseTokenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_parseToken_, context, request, response, std::move(f));
}

void Auth::Stub::async::parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::parseTokenResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_parseToken_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::user::auth::parseTokenResp>* Auth::Stub::PrepareAsyncparseTokenRaw(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::user::auth::parseTokenResp, ::user::auth::parseTokenReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_parseToken_, context, request);
}

::grpc::ClientAsyncResponseReader< ::user::auth::parseTokenResp>* Auth::Stub::AsyncparseTokenRaw(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncparseTokenRaw(context, request, cq);
  result->StartCall();
  return result;
}

Auth::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Auth_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Auth::Service, ::user::auth::getAdminTokenReq, ::user::auth::getAdminTokenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Auth::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::auth::getAdminTokenReq* req,
             ::user::auth::getAdminTokenResp* resp) {
               return service->getAdminToken(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Auth_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Auth::Service, ::user::auth::parseTokenReq, ::user::auth::parseTokenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Auth::Service* service,
             ::grpc::ServerContext* ctx,
             const ::user::auth::parseTokenReq* req,
             ::user::auth::parseTokenResp* resp) {
               return service->parseToken(ctx, req, resp);
             }, this)));
}

Auth::Service::~Service() {
}

::grpc::Status Auth::Service::getAdminToken(::grpc::ServerContext* context, const ::user::auth::getAdminTokenReq* request, ::user::auth::getAdminTokenResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Auth::Service::parseToken(::grpc::ServerContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::parseTokenResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace user
}  // namespace auth

