// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: auth.proto
#ifndef GRPC_auth_2eproto__INCLUDED
#define GRPC_auth_2eproto__INCLUDED

#include "auth.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace user {
namespace auth {

class Auth final {
 public:
  static constexpr char const* service_full_name() {
    return "user.auth.Auth";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 获取用户 token
    virtual ::grpc::Status getUserToken(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq& request, ::user::auth::getUserTokenResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getUserTokenResp>> AsyncgetUserToken(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getUserTokenResp>>(AsyncgetUserTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getUserTokenResp>> PrepareAsyncgetUserToken(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getUserTokenResp>>(PrepareAsyncgetUserTokenRaw(context, request, cq));
    }
    // 解析 token
    virtual ::grpc::Status parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::user::auth::registerUserResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>> AsyncparseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>>(AsyncparseTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>> PrepareAsyncparseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>>(PrepareAsyncparseTokenRaw(context, request, cq));
    }
    // 注册用户
    virtual ::grpc::Status registerUer(::grpc::ClientContext* context, const ::user::auth::registerUserReq& request, ::user::auth::registerUserResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>> AsyncregisterUer(::grpc::ClientContext* context, const ::user::auth::registerUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>>(AsyncregisterUerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>> PrepareAsyncregisterUer(::grpc::ClientContext* context, const ::user::auth::registerUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>>(PrepareAsyncregisterUerRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 获取用户 token
      virtual void getUserToken(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq* request, ::user::auth::getUserTokenResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void getUserToken(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq* request, ::user::auth::getUserTokenResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 解析 token
      virtual void parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::registerUserResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::registerUserResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 注册用户
      virtual void registerUer(::grpc::ClientContext* context, const ::user::auth::registerUserReq* request, ::user::auth::registerUserResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void registerUer(::grpc::ClientContext* context, const ::user::auth::registerUserReq* request, ::user::auth::registerUserResp* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getUserTokenResp>* AsyncgetUserTokenRaw(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::getUserTokenResp>* PrepareAsyncgetUserTokenRaw(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>* AsyncparseTokenRaw(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>* PrepareAsyncparseTokenRaw(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>* AsyncregisterUerRaw(::grpc::ClientContext* context, const ::user::auth::registerUserReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::user::auth::registerUserResp>* PrepareAsyncregisterUerRaw(::grpc::ClientContext* context, const ::user::auth::registerUserReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status getUserToken(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq& request, ::user::auth::getUserTokenResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::getUserTokenResp>> AsyncgetUserToken(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::getUserTokenResp>>(AsyncgetUserTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::getUserTokenResp>> PrepareAsyncgetUserToken(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::getUserTokenResp>>(PrepareAsyncgetUserTokenRaw(context, request, cq));
    }
    ::grpc::Status parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::user::auth::registerUserResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>> AsyncparseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>>(AsyncparseTokenRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>> PrepareAsyncparseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>>(PrepareAsyncparseTokenRaw(context, request, cq));
    }
    ::grpc::Status registerUer(::grpc::ClientContext* context, const ::user::auth::registerUserReq& request, ::user::auth::registerUserResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>> AsyncregisterUer(::grpc::ClientContext* context, const ::user::auth::registerUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>>(AsyncregisterUerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>> PrepareAsyncregisterUer(::grpc::ClientContext* context, const ::user::auth::registerUserReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>>(PrepareAsyncregisterUerRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void getUserToken(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq* request, ::user::auth::getUserTokenResp* response, std::function<void(::grpc::Status)>) override;
      void getUserToken(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq* request, ::user::auth::getUserTokenResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::registerUserResp* response, std::function<void(::grpc::Status)>) override;
      void parseToken(::grpc::ClientContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::registerUserResp* response, ::grpc::ClientUnaryReactor* reactor) override;
      void registerUer(::grpc::ClientContext* context, const ::user::auth::registerUserReq* request, ::user::auth::registerUserResp* response, std::function<void(::grpc::Status)>) override;
      void registerUer(::grpc::ClientContext* context, const ::user::auth::registerUserReq* request, ::user::auth::registerUserResp* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::user::auth::getUserTokenResp>* AsyncgetUserTokenRaw(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::auth::getUserTokenResp>* PrepareAsyncgetUserTokenRaw(::grpc::ClientContext* context, const ::user::auth::getUserTokenReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>* AsyncparseTokenRaw(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>* PrepareAsyncparseTokenRaw(::grpc::ClientContext* context, const ::user::auth::parseTokenReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>* AsyncregisterUerRaw(::grpc::ClientContext* context, const ::user::auth::registerUserReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::user::auth::registerUserResp>* PrepareAsyncregisterUerRaw(::grpc::ClientContext* context, const ::user::auth::registerUserReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getUserToken_;
    const ::grpc::internal::RpcMethod rpcmethod_parseToken_;
    const ::grpc::internal::RpcMethod rpcmethod_registerUer_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 获取用户 token
    virtual ::grpc::Status getUserToken(::grpc::ServerContext* context, const ::user::auth::getUserTokenReq* request, ::user::auth::getUserTokenResp* response);
    // 解析 token
    virtual ::grpc::Status parseToken(::grpc::ServerContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::registerUserResp* response);
    // 注册用户
    virtual ::grpc::Status registerUer(::grpc::ServerContext* context, const ::user::auth::registerUserReq* request, ::user::auth::registerUserResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getUserToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getUserToken() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getUserToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getUserToken(::grpc::ServerContext* /*context*/, const ::user::auth::getUserTokenReq* /*request*/, ::user::auth::getUserTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetUserToken(::grpc::ServerContext* context, ::user::auth::getUserTokenReq* request, ::grpc::ServerAsyncResponseWriter< ::user::auth::getUserTokenResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_parseToken() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestparseToken(::grpc::ServerContext* context, ::user::auth::parseTokenReq* request, ::grpc::ServerAsyncResponseWriter< ::user::auth::registerUserResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_registerUer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_registerUer() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_registerUer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerUer(::grpc::ServerContext* /*context*/, const ::user::auth::registerUserReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestregisterUer(::grpc::ServerContext* context, ::user::auth::registerUserReq* request, ::grpc::ServerAsyncResponseWriter< ::user::auth::registerUserResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getUserToken<WithAsyncMethod_parseToken<WithAsyncMethod_registerUer<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_getUserToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_getUserToken() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::user::auth::getUserTokenReq, ::user::auth::getUserTokenResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::auth::getUserTokenReq* request, ::user::auth::getUserTokenResp* response) { return this->getUserToken(context, request, response); }));}
    void SetMessageAllocatorFor_getUserToken(
        ::grpc::MessageAllocator< ::user::auth::getUserTokenReq, ::user::auth::getUserTokenResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::auth::getUserTokenReq, ::user::auth::getUserTokenResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_getUserToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getUserToken(::grpc::ServerContext* /*context*/, const ::user::auth::getUserTokenReq* /*request*/, ::user::auth::getUserTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getUserToken(
      ::grpc::CallbackServerContext* /*context*/, const ::user::auth::getUserTokenReq* /*request*/, ::user::auth::getUserTokenResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_parseToken() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::user::auth::parseTokenReq, ::user::auth::registerUserResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::auth::parseTokenReq* request, ::user::auth::registerUserResp* response) { return this->parseToken(context, request, response); }));}
    void SetMessageAllocatorFor_parseToken(
        ::grpc::MessageAllocator< ::user::auth::parseTokenReq, ::user::auth::registerUserResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::auth::parseTokenReq, ::user::auth::registerUserResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* parseToken(
      ::grpc::CallbackServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::registerUserResp* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_registerUer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_registerUer() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::user::auth::registerUserReq, ::user::auth::registerUserResp>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::user::auth::registerUserReq* request, ::user::auth::registerUserResp* response) { return this->registerUer(context, request, response); }));}
    void SetMessageAllocatorFor_registerUer(
        ::grpc::MessageAllocator< ::user::auth::registerUserReq, ::user::auth::registerUserResp>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::user::auth::registerUserReq, ::user::auth::registerUserResp>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_registerUer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerUer(::grpc::ServerContext* /*context*/, const ::user::auth::registerUserReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* registerUer(
      ::grpc::CallbackServerContext* /*context*/, const ::user::auth::registerUserReq* /*request*/, ::user::auth::registerUserResp* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_getUserToken<WithCallbackMethod_parseToken<WithCallbackMethod_registerUer<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getUserToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getUserToken() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getUserToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getUserToken(::grpc::ServerContext* /*context*/, const ::user::auth::getUserTokenReq* /*request*/, ::user::auth::getUserTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_parseToken() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_registerUer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_registerUer() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_registerUer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerUer(::grpc::ServerContext* /*context*/, const ::user::auth::registerUserReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getUserToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getUserToken() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getUserToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getUserToken(::grpc::ServerContext* /*context*/, const ::user::auth::getUserTokenReq* /*request*/, ::user::auth::getUserTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetUserToken(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_parseToken() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestparseToken(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_registerUer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_registerUer() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_registerUer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerUer(::grpc::ServerContext* /*context*/, const ::user::auth::registerUserReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestregisterUer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_getUserToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_getUserToken() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getUserToken(context, request, response); }));
    }
    ~WithRawCallbackMethod_getUserToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getUserToken(::grpc::ServerContext* /*context*/, const ::user::auth::getUserTokenReq* /*request*/, ::user::auth::getUserTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* getUserToken(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_parseToken() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->parseToken(context, request, response); }));
    }
    ~WithRawCallbackMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* parseToken(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_registerUer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_registerUer() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->registerUer(context, request, response); }));
    }
    ~WithRawCallbackMethod_registerUer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerUer(::grpc::ServerContext* /*context*/, const ::user::auth::registerUserReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* registerUer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getUserToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getUserToken() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::auth::getUserTokenReq, ::user::auth::getUserTokenResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::auth::getUserTokenReq, ::user::auth::getUserTokenResp>* streamer) {
                       return this->StreamedgetUserToken(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getUserToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getUserToken(::grpc::ServerContext* /*context*/, const ::user::auth::getUserTokenReq* /*request*/, ::user::auth::getUserTokenResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetUserToken(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::auth::getUserTokenReq,::user::auth::getUserTokenResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_parseToken : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_parseToken() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::auth::parseTokenReq, ::user::auth::registerUserResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::auth::parseTokenReq, ::user::auth::registerUserResp>* streamer) {
                       return this->StreamedparseToken(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_parseToken() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status parseToken(::grpc::ServerContext* /*context*/, const ::user::auth::parseTokenReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedparseToken(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::auth::parseTokenReq,::user::auth::registerUserResp>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_registerUer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_registerUer() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::user::auth::registerUserReq, ::user::auth::registerUserResp>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::user::auth::registerUserReq, ::user::auth::registerUserResp>* streamer) {
                       return this->StreamedregisterUer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_registerUer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status registerUer(::grpc::ServerContext* /*context*/, const ::user::auth::registerUserReq* /*request*/, ::user::auth::registerUserResp* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedregisterUer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::user::auth::registerUserReq,::user::auth::registerUserResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getUserToken<WithStreamedUnaryMethod_parseToken<WithStreamedUnaryMethod_registerUer<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getUserToken<WithStreamedUnaryMethod_parseToken<WithStreamedUnaryMethod_registerUer<Service > > > StreamedService;
};

}  // namespace auth
}  // namespace user


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_auth_2eproto__INCLUDED
